# Generated by Django 6.0.7 on 2026-08-04 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=20)),
                ('font_size', models.CharField(choices=[('default', 'Default'), ('large', 'Large'), ('extra-large', 'Extra Large')], default='default', max_length=20)),
                ('color_scheme', models.CharField(choices=[('orange', 'Orange'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red')], default='orange', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
